# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WwuUdE07Jd7PW_oA8wSs9rk8Ch8BIvAH
"""

import streamlit as st
import feedparser
from openai import OpenAI

# 1. 웹 화면 기본 설정
st.set_page_config(page_title="나만의 기술 뉴스 요약봇", layout="wide")
st.title("아침을 여는 맞춤형 기술 뉴스 3줄 요약")
st.caption("해외 RSS 피드에서 최신 IT 글을 가져와 AI가 한국어로 핵심만 요약합니다.")

# 2. 사이드바 설정 (API Key 입력 및 매체 선택)
st.sidebar.header("설정 및 입력")
api_key = st.sidebar.text_input("OpenAI API Key를 입력하세요", type="password")

RSS_FEEDS = {
    "TechCrunch (전반적인 테크 뉴스)": "https://techcrunch.com/feed/",
    "The Verge (IT/가전/문화)": "https://www.theverge.com/rss/index.xml",
    "Wired (심층 기술 분석)": "https://www.wired.com/feed/rss"
}
category = st.sidebar.selectbox("뉴스 매체 선택", list(RSS_FEEDS.keys()))

# 3. LLM 요약 함수 (gpt-4o-mini 모델 활용)
def summarize_text(text, api_key):
    if not api_key:
        return "요약을 시작하려면 좌측 사이드바에 OpenAI API Key를 입력해 주세요."

    try:
        client = OpenAI(api_key=api_key)
        # 긴 글 토큰 제한 및 비용 방지를 위한 텍스트 커팅 (Chunking)
        truncated_text = text[:3000]

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "너는 IT 기술 전문 요약가야. 입력받은 영문 기사 내용을 바탕으로 전하고자 하는 핵심 정보를 반드시 한국어 딱 3줄(문장)로 깔끔하게 요약해줘. 번역 투를 지양하고 자연스러운 한국어로 명확하게 작성해줘."},
                {"role": "user", "content": f"기사 본문:\n{truncated_text}"}
            ],
            max_tokens=300,
            temperature=0.5
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"요약 중 오류 발생: {str(e)}"

# 4. 메인 화면 구동 버튼 및 뉴스 카드 배치
if st.button("최신 뉴스 가져오기 및 요약 시작"):
    if not api_key:
        st.error("좌측 사이드바에 OpenAI API Key를 먼저 입력한 뒤 버튼을 눌러주세요!")
    else:
        with st.spinner("RSS 피드를 분석하고 AI가 열심히 요약하는 중입니다..."):
            feed = feedparser.parse(RSS_FEEDS[category])
            entries = feed.entries[:6] # 최신 글 6개 수집

            if not entries:
                st.warning("가져올 신규 글이 없습니다.")
            else:
                # 2열 격자(Grid) 구조로 카드 배치하여 가독성 확보
                cols = st.columns(2)

                for idx, entry in enumerate(entries):
                    col = cols[idx % 2] # 좌우 번갈아가며 배치

                    with col:
                        with st.container(border=True): # 테두리가 있는 카드 형태
                            st.subheader(entry.title)
                            st.caption(f"발행일: {entry.get('published', '날짜 정보 없음')}")

                            # 뉴스 본문 추출 및 요약
                            summary_text = entry.get('summary', entry.get('description', ''))
                            ai_summary = summarize_text(summary_text, api_key)

                            # 요약본 출력
                            st.markdown("**AI 3줄 한국어 요약:**")
                            st.info(ai_summary)

                            # 원문 보기 링크 버튼
                            st.link_button("원문 기사 보러가기 🔗", entry.link)